name: Crayon-GraveStones
main: at.slini.crayonsmp.graves.GravePlugin
version: 1.3.0-HOTFIX
api-version: "1.21"
authors: [ "SLINIcraftet204" ]
description: Gravestones with configurable loot/ownership rules.
commands:
  graves:
    description: Crayon-GraveStones commands.
    usage: /graves <reload|list>
    permission: graves.use
permissions:
  graves.use:
    default: true
  graves.admin:
    default: op
