name: better-GraveStones
main: at.slini204.bgravestones.GravePlugin
version: 2.7.0
api-version: "1.21"
authors: [ "SLINIcraftet204" ]
description: Gravestones with configurable loot/ownership rules.
commands:
  graves:
    description: bGraveStones commands.
    usage: /graves <reload|list>
    permission: graves.use
permissions:
  graves.use:
    default: true
  graves.admin:
    default: op
